Feature/n UI 2765 y axis opacity
solarwinds/nova pull request #181
Opened 2021-03-19 22:27 UTC by lukasholcik

2021-03-23 17:35 UTC, Blakesalot requested changes

2021-03-23 17:35 UTC, Blakesalot commented on packages/charts/src/core/grid/xy-grid.spec.ts
> +        fit("highlights axes", () => {
fit

2021-03-23 17:47 UTC, Blakesalot requested changes

2021-03-23 17:47 UTC, Blakesalot commented on packages/charts/examples/components/demo/advanced-usage/events/chart-docs-events.component.html
> +    Triggered when the an XY grid with two Y axes changes opacity due to series related to one of the Y axes being emphasized.
```suggestion
    Triggered when the right or left axis of an XY grid with two Y axes changes its opacity due to a change in series emphasis.
```

2021-03-23 17:47 UTC, Blakesalot commented on packages/charts/examples/components/demo/advanced-usage/events/chart-docs-events.component.html
> +    <code><a href="../interfaces/IChartViewStatusEventPayload.html" target="_blank">IChartViewStatusEventPayload</a></code>.
```suggestion
    <code><a href="../interfaces/IXYGridOpacityEventPayload.html" target="_blank">IXYGridOpacityEventPayload</a></code>.
```

2021-03-23 17:47 UTC, Blakesalot commented on packages/charts/examples/components/demo/chart-types/line/line-chart-with-2y-axes/line-chart-with-2y-axes-example.component.ts
> +        //
is there supposed to be a comment to the consumer here?

2021-03-23 17:47 UTC, Blakesalot commented on packages/charts/examples/components/demo/advanced-usage/events/chart-docs-events.component.html
> +<h4><a href="../miscellaneous/variables.html#XY_GRID_AXES_OPACITY_EVENT" target="_blank">XY_GRID_AXES_OPACITY_EVENT</a></h4>
It would be nice to add this to the event sampler. But, adding a legend will conflict with @madelyneh's work for the "series visibility" event docs.

2021-03-23 21:05 UTC, lukasholcik commented on packages/charts/src/core/grid/types.ts
> +    eventBus: EventBus<IChartEvent>;
It's assigned by the chart to every grid, so it is not optional.

2021-03-24 19:50 UTC, Blakesalot submitted a review, later dismissed

2021-03-24 19:57 UTC, Blakesalot approved these changes

2021-03-25 16:18 UTC, elenates approved these changes

2021-03-25 21:30 UTC, merged