oo-8567 timeseries legend menu
solarwinds/nova pull request #518
Opened 2023-01-25 14:24 UTC by findo11

2023-01-25 16:02 UTC, stepanstava requested changes

2023-01-25 16:02 UTC, stepanstava commented on packages/dashboards/src/lib/components/timeseries-widget/chart-presets/timeseries-chart.component.ts
> +                        serie.data = serie.transformer(serie.rawData);
same here, could we do the copy only in the case that the transormation will be applied?

````
if (serie.transformer && serie.data.length > 0) {
  serie.rawData = [...serie.data];
  serie.data = serie.transformer(serie.data);
}
````

2023-01-30 08:16 UTC, stepanstava submitted a review, later dismissed

2023-01-30 14:06 UTC, stepanstava approved these changes

2023-01-30 22:29 UTC, mzknksh requested changes

2023-01-30 22:29 UTC, mzknksh commented on packages/dashboards/src/lib/components/timeseries-widget/transformer/loess.ts
> +// Based on org.apache.commons.math.analysis.interpolation.LoessInterpolator
we should also include the comment header to newly added the source files (keep these, but prepend the SWI text as seen in other sourcefiles)

(did we check the original license in these? just to be sure)

2023-01-31 19:50 UTC, mzknksh approved these changes

2023-02-06 13:22 UTC, stepanstava approved these changes

2023-02-06 15:11 UTC, merged