OO-5867 update y axis domain
solarwinds/nova pull request #531
Opened 2023-03-10 14:28 UTC by findo11

2023-03-13 07:59 UTC, stepanstava requested changes

2023-03-14 12:18 UTC, stepanstava commented on packages/dashboards/src/lib/components/timeseries-widget/timeseries-helpers.ts
> +        .reduce((x, y) => x.concat(y), []);
isn't this flatMap()?
https://github.com/solarwinds/orion/blob/main/src/frontend/fusion/packages/platform-sdk/src/dashboard/datasources/timeseries/perfstack-metrics-converter/perfstack-metrics-utils.ts#L49

2023-03-14 12:19 UTC, jirkapok approved these changes

2023-03-14 12:19 UTC, jirkapok commented on packages/dashboards/src/lib/components/timeseries-widget/chart-presets/timeseries-chart.component.ts
> +                        this.widgetData.series as any,
Are we able to avoid any?

2023-03-14 12:21 UTC, stepanstava commented on packages/dashboards/src/lib/components/timeseries-widget/chart-presets/timeseries-chart.component.ts
> +                        this.widgetData.series as any,
why any here?

2023-03-14 14:49 UTC, stepanstava approved these changes

2023-03-14 14:51 UTC, stepanstava requested changes
percy dashboards tests:
Before:
![image](https://user-images.githubusercontent.com/48520954/225039997-9bda1173-d581-4d02-b69f-8513ca858399.png)

After:
![image](https://user-images.githubusercontent.com/48520954/225039876-7ecca519-2a3c-48e5-9b6d-9e14304b6bef.png)

2023-03-15 12:55 UTC, stepanstava approved these changes

2023-03-15 13:11 UTC, merged